FROM node:13-stretch as builder

WORKDIR /build

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN yarn build

FROM nginx:1.13-alpine
COPY --from=builder /build/dist /usr/share/nginx/html
